import pytest

import numpy as np
from pyscf import gto, scf

threshold = 1.0e-7

def get_wavefunction_and_integrals():
    import h5py
    from jax import numpy as jnp

    with h5py.File("FCIDUMP_chol", "r") as fh5:
        [nelec, nmo, ms, nchol] = fh5["header"]
        h0 = jnp.array(fh5.get("energy_core"))
        h1 = jnp.array(fh5.get("hcore")).reshape(nmo, nmo)
        chol = jnp.array(fh5.get("chol")).reshape(-1, nmo, nmo)

    ms, nelec, nmo, nchol = int(ms), int(nelec), int(nmo), int(nchol)
    nelec_sp = ((nelec + abs(ms)) // 2, (nelec - abs(ms)) // 2)
    norb = nmo

    ham_data = {}
    ham_data["h0"] = h0
    ham_data["h1"] = jnp.array([h1, h1])
    ham_data["chol"] = chol.reshape(nchol, -1)
    ham_data["ene0"] = 0.0e0

    wave_data = {}
    mo_coeff = jnp.array(np.load("mo_coeff.npz")["mo_coeff"])

    amplitudes = np.load("amplitudes.npz")

    ci1a = jnp.array(amplitudes["ci1a"])
    ci1b = jnp.array(amplitudes["ci1b"])

    ci2aa = jnp.array(amplitudes["ci2aa"])
    ci2ab = jnp.array(amplitudes["ci2ab"])
    ci2bb = jnp.array(amplitudes["ci2bb"])

    ci3aaa = jnp.array(amplitudes["ci3aaa"])
    ci3aab = jnp.array(amplitudes["ci3aab"])
    ci3abb = jnp.array(amplitudes["ci3abb"])
    ci3bbb = jnp.array(amplitudes["ci3bbb"])

    ci4aaaa = jnp.array(amplitudes["ci4aaaa"])
    ci4aaab = jnp.array(amplitudes["ci4aaab"])
    ci4aabb = jnp.array(amplitudes["ci4aabb"])
    ci4abbb = jnp.array(amplitudes["ci4abbb"])
    ci4bbbb = jnp.array(amplitudes["ci4bbbb"])

    trial_wave_data = {
        "ci1A": ci1a,
        "ci1B": ci1b,
        "ci2AA": ci2aa,
        "ci2AB": ci2ab,
        "ci2BB": ci2bb,
        "ci3AAA": ci3aaa,
        "ci3AAB": ci3aab,
        "ci3ABB": ci3abb,
        "ci3BBB": ci3bbb,
        "ci4AAAA": ci4aaaa,
        "ci4AAAB": ci4aaab,
        "ci4AABB": ci4aabb,
        "ci4ABBB": ci4abbb,
        "ci4BBBB": ci4bbbb,
        "mo_coeff": mo_coeff,
    }

    wave_data.update(trial_wave_data)

    from ad_afqmc import wavefunctions
    trial = wavefunctions.UCISDTQ(norb, nelec_sp, n_batch=1)

    ham_data = trial._build_measurement_intermediates(ham_data, wave_data)

    return trial, wave_data, ham_data, nelec_sp    

def compute_and_test_reference_and_rotated_overlaps_energies(mol, nfrozen=0, 
    rotated_eq_unrotated=False, compare_ebcc_manual=False,
    cc_method="ccsdtq", order=4):
    mol.verbose = 4
    mf = scf.UHF(mol)
    mf.max_cycle=300
    mf.run(conv_tol=1e-14)
    if not mf.converged:
        print("Could not converge SCF!")
        exit(1)

    from ccpy.drivers.driver import Driver

    driver = Driver.from_pyscf(mf, nfrozen=nfrozen, uhf=True)
    driver.options["amp_convergence"] = 1.0e-14
    driver.options["energy_convergence"] = 1.0e-14
    driver.options["RHF_symmetry"] = False
    driver.system.print_info()

    driver.run_cc(method=cc_method)

    # Prepare amplitudes
    from ad_afqmc import ccpy_interface
    ci_amps = list(ccpy_interface.prepare_ucc_amplitudes_from_ccpy(driver, get_amps=True, order=order))
    ci_amps = [list(x) if isinstance(x, tuple) else [x] for x in ci_amps]
    ci_amps = [[x / ci_amps[0][0] for x in xs] for xs in ci_amps]

    if compare_ebcc_manual:
        # Get the CI amplitudes using ebcc and compare with manual conversion
        from ad_afqmc import cc_2_ci
        t, (c1, c2, c3, c4) = cc_2_ci.uci_from_ccpy(mf, driver, order)
        ci_amps_e = list([np.float64(1.0), c1, c2, c3, c4])
        ci_amps_e = [list(x) if isinstance(x, tuple) else [x] for x in ci_amps_e]
        ci_amps_e = [[x / ci_amps_e[0][0] for x in xs] for xs in ci_amps_e]

    # Prepare integrals
    from ad_afqmc import pyscf_interface
    pyscf_interface.prep_afqmc(mf, norb_frozen=nfrozen, chol_cut=1.0e-14, basis_coeff=mf.mo_coeff[0])

    trial, wave_data, ham_data, nelec_sp = get_wavefunction_and_integrals()

    # Compute overlap/energy for unrotated walker (equal to the trial reference determinant)
    c0, c1 = wave_data["mo_coeff"][0][:,:nelec_sp[0]], wave_data["mo_coeff"][1][:,:nelec_sp[1]]

    ene_afqmc_0 = trial._calc_energy(c0, c1, ham_data, wave_data)
    overlap_0 = trial._calc_overlap(c0, c1, wave_data)

    # Compute overlap/energy for randomly rotated walker
    seed_value = 82  # You can choose any integer seed
    np.random.seed(seed_value) 

    rand0 = np.random.rand(mol.nao, mol.nao)
    rand1 = np.random.rand(mol.nao, mol.nao)

    u0_f = wave_data["mo_coeff"][0] @ rand0
    u1_f = wave_data["mo_coeff"][1] @ rand1

    u0 = u0_f[:,:nelec_sp[0]]
    u1 = u1_f[:,:nelec_sp[1]]

    ene_afqmc_r = trial._calc_energy(u0, u1, ham_data, wave_data)
    overlap_r = trial._calc_overlap(u0, u1, wave_data)

    # Compute overlap/energy with autogenerated code
    from ad_afqmc import hamiltonian_noci_overlaps, noci_overlaps 

    det_mo = np.array([mf.mo_coeff[0] @ rand0, mf.mo_coeff[1] @ rand1])

    ham_overlap_auto_0 = hamiltonian_noci_overlaps.evaluate(mf, ci_amps, mf.mo_coeff)
    overlap_auto_0 = noci_overlaps.evaluate(mf, ci_amps, mf.mo_coeff)

    energy_auto_0 = ham_overlap_auto_0/overlap_auto_0 + mol.energy_nuc()

    ham_overlap_auto_r = hamiltonian_noci_overlaps.evaluate(mf, ci_amps, det_mo)
    overlap_auto_r = noci_overlaps.evaluate(mf, ci_amps, det_mo)

    energy_auto_r = ham_overlap_auto_r/overlap_auto_r + mol.energy_nuc()

    if compare_ebcc_manual:
        overlap_auto_0_e = noci_overlaps.evaluate(mf, ci_amps_e, mf.mo_coeff)
        overlap_auto_r_e = noci_overlaps.evaluate(mf, ci_amps_e, det_mo)
        print(f"\n## Overlaps according auto-generated code using EBCC and manual conversion:\n")
        print(f"Reference determinant (auto-manual): {overlap_auto_0}")
        print(f"Reference determinant (auto-ebcc):   {overlap_auto_0_e}\n")
        print(f"Rotated determinant (auto-manual):   {overlap_auto_r}")
        print(f"Rotated determinant (auto-ebcc):     {overlap_auto_r_e}")
        assert np.abs(overlap_auto_0-overlap_auto_0_e) < 1.0e-15
        assert np.abs(overlap_auto_r-overlap_auto_r_e) < 1.0e-15

    print(f"\n## Overlaps according to AFQMC and auto-generated code:\n")
    print(f"Reference determinant (AFQMC): {overlap_0}")
    print(f"Reference determinant (auto):  {overlap_auto_0}\n")
    print(f"Rotated determinant (AFQMC):   {overlap_r}")
    print(f"Rotated determinant (auto):    {overlap_auto_r}")

    print(f"\n## Energies according to AFQMC and auto-generated code:\n")
    print(f"Reference determinant (AFQMC): {ene_afqmc_0.real.item()}")
    print(f"Reference determinant (auto):  {energy_auto_0}\n")
    print(f"Rotated determinant (AFQMC):   {ene_afqmc_r.real.item()}")
    print(f"Rotated determinant (auto):    {energy_auto_r}")

    assert np.abs(overlap_auto_0-overlap_0) < 1.0e-12
    assert np.abs(overlap_auto_r-overlap_r) < 1.0e-12

    # 1.0e-5 as we are using AD code which
    # has limited accuracy in the energy due to numerical 
    # central differences differentiation
    assert np.abs(energy_auto_0-ene_afqmc_0) < 1.0e-5
    assert np.abs(energy_auto_r-ene_afqmc_r) < 1.0e-5

    if rotated_eq_unrotated:
        # Check that rotated and unrotated energy is equal
        # This allows to check that rotated determinants have a fixed
        # energy in the FCI limit
        assert np.abs(energy_auto_r-ene_afqmc_0) < 1.0e-5


def test_heh2_ccsdtq():
    # aabb block
    mol = gto.M(atom="H 0 0 0; H 0 0 1.1; He 0 1.7 0", basis="6-31g", symmetry="c1", verbose=0, charge=0, spin=0)
    # Below, rotated_eq_unrotated=True because FCI limit
    # => Energy the same for every rotated determinant
    compute_and_test_reference_and_rotated_overlaps_energies(mol, rotated_eq_unrotated=True) 

    # aaab block
    mol = gto.M(atom="H 0 0 0; H 0 0 1.1; He 0 1.7 0", basis="6-31g", symmetry="c1", verbose=0, charge=0, spin=2)
    compute_and_test_reference_and_rotated_overlaps_energies(mol, rotated_eq_unrotated=True) 


def test_beh2_ccsdtq():
    mol = gto.M(atom="H 0 0 0; H 0 0 1.1; Be 0 1.7 0", basis="sto-3g", symmetry="c1", verbose=0, charge=0, spin=0)
    # checks all blocks except aaaa/bbbb in comparison
    compute_and_test_reference_and_rotated_overlaps_energies(mol, compare_ebcc_manual=True)

def test_he4_ccsdtq():
    mol = gto.M(atom="He 0 0 0; He 0 0 1.1; He 0 1.7 0; He 1.1 0 0", basis="6-31g", symmetry="c1", verbose=0, charge=0, spin=0)
    # tests all blocks in ebcc-manual conversion
    compute_and_test_reference_and_rotated_overlaps_energies(mol, compare_ebcc_manual=True)

def test_he4_ccsdt_q():
    mol = gto.M(atom="He 0 0 0; He 0 0 1.1; He 0 1.7 0; He 1.1 0 0", basis="6-31g", symmetry="c1", verbose=0, charge=0, spin=0)
    # tests all blocks in ebcc-manual conversion
    # ccsdt -> disconnected q
    compute_and_test_reference_and_rotated_overlaps_energies(mol, 
        compare_ebcc_manual=True, cc_method="ccsdt", order=4)

def test_he4_ccsd_tq():
    mol = gto.M(atom="He 0 0 0; He 0 0 1.1; He 0 1.7 0; He 1.1 0 0", basis="6-31g", symmetry="c1", verbose=0, charge=0, spin=0)
    # tests all blocks in ebcc-manual conversion
    # ccsd -> disconnected tq
    compute_and_test_reference_and_rotated_overlaps_energies(mol, 
        compare_ebcc_manual=True, cc_method="ccsd", order=4)


if __name__ == "__main__":
    import jax
    jax.config.update("jax_enable_x64", True)

    test_heh2_ccsdtq()
    test_beh2_ccsdtq()
    test_he4_ccsdtq()
    test_he4_ccsdt_q()
    test_he4_ccsd_tq()
