import pytest

import numpy as np
from pyscf import gto, scf

threshold = 1.0e-7

def get_wavefunction_and_integrals():
    import h5py
    from jax import numpy as jnp

    with h5py.File("FCIDUMP_chol", "r") as fh5:
        [nelec, nmo, ms, nchol] = fh5["header"]
        h0 = jnp.array(fh5.get("energy_core"))
        h1 = jnp.array(fh5.get("hcore")).reshape(nmo, nmo)
        chol = jnp.array(fh5.get("chol")).reshape(-1, nmo, nmo)

    ms, nelec, nmo, nchol = int(ms), int(nelec), int(nmo), int(nchol)
    nelec_sp = ((nelec + abs(ms)) // 2, (nelec - abs(ms)) // 2)
    norb = nmo

    ham_data = {}
    ham_data["h0"] = h0
    ham_data["h1"] = jnp.array([h1, h1])
    ham_data["chol"] = chol.reshape(nchol, -1)
    ham_data["ene0"] = 0.0e0

    wave_data = {}
    mo_coeff = jnp.array(np.load("mo_coeff.npz")["mo_coeff"])

    amplitudes = np.load("amplitudes.npz")

    ci1a = jnp.array(amplitudes["ci1a"])
    ci1b = jnp.array(amplitudes["ci1b"])

    ci2aa = jnp.array(amplitudes["ci2aa"])
    ci2ab = jnp.array(amplitudes["ci2ab"])
    ci2bb = jnp.array(amplitudes["ci2bb"])

    ci3aaa = jnp.array(amplitudes["ci3aaa"])
    ci3aab = jnp.array(amplitudes["ci3aab"])
    ci3abb = jnp.array(amplitudes["ci3abb"])
    ci3bbb = jnp.array(amplitudes["ci3bbb"])

    trial_wave_data = {
        "ci1A": ci1a,
        "ci1B": ci1b,
        "ci2AA": ci2aa,
        "ci2AB": ci2ab,
        "ci2BB": ci2bb,
        "ci3AAA": ci3aaa,
        "ci3AAB": ci3aab,
        "ci3ABB": ci3abb,
        "ci3BBB": ci3bbb,
        "mo_coeff": mo_coeff,
    }

    wave_data.update(trial_wave_data)

    from ad_afqmc import wavefunctions
    trial = wavefunctions.ucisdt(norb, nelec_sp, n_batch=1)

    ham_data = trial._build_measurement_intermediates(ham_data, wave_data)

    return trial, wave_data, ham_data, nelec_sp    

def compute_and_test_reference_and_rotated_overlaps_energies(mol):
    mol.verbose = 4
    mf = scf.UHF(mol)
    mf.max_cycle=300
    mf.run(conv_tol=1e-14)
    if not mf.converged:
        print("Could not converge SCF!")
        exit(1)

    from ccpy.drivers.driver import Driver

    driver = Driver.from_pyscf(mf, nfrozen=0, uhf=True)
    driver.options["amp_convergence"] = 1.0e-14
    driver.options["energy_convergence"] = 1.0e-14
    driver.options["RHF_symmetry"] = False
    driver.system.print_info()

    driver.run_cc(method="ccsdt")

    # Prepare amplitudes
    from ad_afqmc import ccpy_interface
    ci_amps = list(ccpy_interface.prepare_ucc_amplitudes_from_ccpy(driver, get_amps=True))

    # Prepare integrals
    from ad_afqmc import pyscf_interface
    pyscf_interface.prep_afqmc(mf, norb_frozen=0, chol_cut=1.0e-14, basis_coeff=mf.mo_coeff[0])

    trial, wave_data, ham_data, nelec_sp = get_wavefunction_and_integrals()

    # Compute overlap/energy for unrotated walker (equal to the trial reference determinant)
    c0, c1 = wave_data["mo_coeff"][0][:,:nelec_sp[0]], wave_data["mo_coeff"][1][:,:nelec_sp[1]]

    ene_afqmc_0 = trial._calc_energy(c0, c1, ham_data, wave_data)
    overlap_0 = trial._calc_overlap(c0, c1, wave_data)

    # Compute overlap/energy for randomly rotated walker
    seed_value = 82  # You can choose any integer seed
    np.random.seed(seed_value) 

    rand0 = np.random.rand(mol.nao, mol.nao)
    rand1 = np.random.rand(mol.nao, mol.nao)

    u0 = ( wave_data["mo_coeff"][0] @ rand0 )[:,:nelec_sp[0]]
    u1 = ( wave_data["mo_coeff"][1] @ rand1 )[:,:nelec_sp[1]]

    ene_afqmc_r = trial._calc_energy(u0, u1, ham_data, wave_data)
    overlap_r = trial._calc_overlap(u0, u1, wave_data)

    # Compute overlap/energy with autogenerated code
    from ad_afqmc import hamiltonian_noci_overlaps, noci_overlaps 

    det_mo = np.array([mf.mo_coeff[0] @ rand0, mf.mo_coeff[1] @ rand1])

    ci_amps = [list(x) if isinstance(x, tuple) else [x] for x in ci_amps]
    ci_amps = [[x / ci_amps[0][0] for x in xs] for xs in ci_amps]

    ham_overlap_auto_0 = hamiltonian_noci_overlaps.evaluate(mf, ci_amps, mf.mo_coeff)
    overlap_auto_0 = noci_overlaps.evaluate(mf, ci_amps, mf.mo_coeff)

    energy_auto_0 = ham_overlap_auto_0/overlap_auto_0 + mol.energy_nuc()

    ham_overlap_auto_r = hamiltonian_noci_overlaps.evaluate(mf, ci_amps, det_mo)
    overlap_auto_r = noci_overlaps.evaluate(mf, ci_amps, det_mo)

    energy_auto_r = ham_overlap_auto_r/overlap_auto_r + mol.energy_nuc()

    print(f"\n## Overlaps according to AFQMC and auto-generated code:\n")
    print(f"Reference determinant (AFQMC): {overlap_0}")
    print(f"Reference determinant (auto):  {overlap_auto_0}\n")
    print(f"Rotated determinant (AFQMC):   {overlap_r}")
    print(f"Rotated determinant (auto):    {overlap_auto_r}")

    print(f"\n## Energies according to AFQMC and auto-generated code:\n")
    print(f"Reference determinant (AFQMC): {ene_afqmc_0.real.item()}")
    print(f"Reference determinant (auto):  {energy_auto_0}\n")
    print(f"Rotated determinant (AFQMC):   {ene_afqmc_r.real.item()}")
    print(f"Rotated determinant (auto):    {energy_auto_r}")

    assert np.abs(overlap_auto_0-overlap_0) < 1.0e-12
    assert np.abs(overlap_auto_r-overlap_r) < 1.0e-12

    assert np.abs(energy_auto_0-ene_afqmc_0) < 1.0e-12
    assert np.abs(energy_auto_r-ene_afqmc_r) < 1.0e-12

def test_hf_ccsdt():
    mol = gto.M(atom="H 0 0 0; F 1.2 0.0 0.0", basis="6-31g", symmetry="c1", verbose=0)
    compute_and_test_reference_and_rotated_overlaps_energies(mol)

def test_h2o_ccsdt():
    mol = gto.M(atom="H 0 0 0; H 0 0 1.1; O 0 1.7 0", basis="3-21g", symmetry="c1", verbose=0, charge=1, spin=3)
    compute_and_test_reference_and_rotated_overlaps_energies(mol)

def test_beh2he_ccsdt():
    mol = gto.M(atom="H 0 0 0; H 0 0 1.1; Be 0 1.7 0; He 7.0 0.0 0.0", basis="6-31g", symmetry="c1", verbose=0)
    compute_and_test_reference_and_rotated_overlaps_energies(mol)

def test_h3_ccsdt():
    mol = gto.M(atom="H 0 0 0; H 0 0 1.1; H 0 1.7 0", basis="6-31g", symmetry="c1", verbose=0, charge=0, spin=1)
    compute_and_test_reference_and_rotated_overlaps_energies(mol)

if __name__ == "__main__":
    import jax
    jax.config.update("jax_enable_x64", True)

    #test_h3_ccsdt()
    #test_h2o_ccsdt()
    #test_beh2he_ccsdt()
    test_hf_ccsdt()
